# Generated by Django 5.2 on 2025-04-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
